version: 1.0.{build}
image: Visual Studio 2017
init:
- ps: Install-Product node $env:nodejs_version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nodejs_version: 11
install:
- cmd: >-
    git submodule sync --recursive
    git submodule update --init --recursive
build_script:
- cmd: >-
    dotnet deb -r ubuntu.16.04-x64   -f netcoreapp2.2 -c Release
    dotnet rpm  -r  rhel.7-x64   -f netcoreapp2.2 -c Release
    dotnet zip   -r  win7-x64   -f netcoreapp2.2 -c Release
artifacts:
- path: IoTSharp\bin\Release\netcoreapp2.2\linux-x64\publish\
  name: IoTSharp-linux-x64