version: 1.0.{build}
image: Visual Studio 2019
init:
- ps: Install-Product node $env:nodejs_version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nodejs_version: 11
install:
- cmd: >-
    git submodule sync --recursive

    git submodule update --init --recursive

    dotnet tool install --global dotnet-zip

    dotnet tool install --global dotnet-tarball

    dotnet tool install --global dotnet-rpm

    dotnet tool install --global dotnet-deb
build_script:
- cmd: "dotnet msbuild IoTSharp/IoTSharp.csproj /t:CreateDeb  /p:TargetFramework=netcoreapp3.0  /p:RuntimeIdentifier=ubuntu.16.04-x64  \n       /p:Configuration=Release \ndotnet msbuild IoTSharp/IoTSharp.csproj /t:CreateRpm \n       /p:TargetFramework=netcoreapp3.0 /p:RuntimeIdentifier=rhel.7-x64 \n        /p:Configuration=Release\ndotnet msbuild IoTSharp/IoTSharp.csproj /t:CreateZip \n      /p:TargetFramework=netcoreapp3.0 /p:RuntimeIdentifier=win7-x64 \n       /p:Configuration=Release"
artifacts:
- path: IoTSharp\bin\Release\netcoreapp3.0\ubuntu.16.04-x64\*.deb
  name: IoTSharp.ubuntu
- path: IoTSharp\bin\Release\netcoreapp3.0\rhel.7-x64\*.rpm
  name: IoTSharp.centos
- path: IoTSharp\bin\Release\netcoreapp3.0\win7-x64\*.zip
  name: IoTSharp.win