version: 1.0.{build}
image: Visual Studio 2017
init:
- ps: Install-Product node $env:nodejs_version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nodejs_version: 11
install:
- cmd: >-
    git submodule sync --recursive
    
    git submodule update --init --recursive
build_script:
- cmd: >-
    dotnet publish  -r  linux-x64   -c Release
    
    rmdir IoTSharp\bin\Release\netcoreapp2.2\linux-x64\publish\ClientApp\node_modules   /S/Q
artifacts:
- path: IoTSharp\bin\Release\netcoreapp2.2\linux-x64\publish\
  name: IoTSharp-linux-x64