version: '3.4'

services:
  iotsharp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "2927::80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    build:
      context: .
      dockerfile: IoTSharp/Dockerfile
  