[build]
  publish = "iotsharp/public"
  command = "hugo -s iotsharp"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
  HUGO_VERSION = "0.50"

[context.production.environment]
  HUGO_BASEURL = "https://docs.iotsharp.io/"

[context.deploy-preview]
  command = "hugo -s iotsharp -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"

[context.branch-deplpy]
  command = "hugo -s iotsharp -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"

