name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-dotnet@v1.5.0
    - name: Setup .NET Core
    - name: Build with dotnet
      run: dotnet build IoTSharp.sln --configuration Release
