baseURL = "/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"

title = "IoTSharp Documentation"
theme = "docs"
themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/iotsharp/iotsharp/edit/master/docs/iotsharp/content/"
  description = "Documentation for IoTSharp"
  author = "maikebing"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for IoTSharp"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/iotsharp/iotsharp"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> IoTSharp Home Page"
identifier = "iotsharhome"
url = "https://iotsharp.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[Languages.zh-cn]
title = "IoTSharp 文档"
weight = 2
languageName = "简体中文"

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i>Github版本库"
identifier = "ds"
url = "https://github.com/iotsharp/iotsharp"
weight = 10

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> 案例"
url = "/showcase"
weight = 11

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> IoTSharp 首页"
identifier = "iotsharpdoc"
url = "https://iotsharp.io/"
weight = 20

[[Languages.zh-cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 鸣谢"
url = "/credits"
weight = 30
